spring:
 datasource:
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://localhost:3306/springboottest
   username: root
   password: root
 jpa:
   database: MYSQL
   generate-ddl: true
   hibernate:
     ddl-auto: update

